### PR TITLE
Scratch links added

### PR DESCRIPTION
**Pull request by Quantum-Codes**

### CODE REVIEW

**Comment by BarelySmooth** [comment]
Thanks for this! But I left this out intentionally and I'll put a different link there soon 😃

**Comment by Quantum-Codes** [comment]
Why :(

**Comment by Quantum-Codes** [comment]
Hello

**Comment by BarelySmooth** [comment]
I'm planning to get a new account and I think I'll advertise the website there :)

**Comment by Quantum-Codes** [comment]
0

> I'm planning to get a new username and I think I'll advertise the website there :)

OHHH thats what u meant in your WIWO!!!! (BTW it took 5 mins to find ur spelling. sorry)
And I am also waiting for 30 days for ST to read my mail AKA appeal :(

**Comment by Quantum-Codes** [comment]
But its hard... if your name is revealed in your username, its easy to change. Anyways.. good luck on that

**Comment by BarelySmooth** [comment]
> But its hard... if your name is revealed in your username, its easy to change. Anyways.. good luck on that

Thanks, I have waited for a long time so I think they'll read it soon

**Comment by Quantum-Codes** [comment]
K

**Comment by BarelySmooth** [comment]
I have added the link in the header and the footer (in commit 3e2dfa1)

**Comment by Quantum-Codes** [comment]
This morning u had previous one?!

**Comment by BarelySmooth** [comment]
Yesterday I had the previous one

**Comment by Quantum-Codes** [comment]
CONGRATS!!! BTW when did u send the mail and how long did they took to respond

**Comment by BarelySmooth** [comment]
> CONGRATS!!! BTW when did u send the mail and how long did they took to respond

Thanks! I sent it more than 2 months ago

**Comment by Quantum-Codes** [comment]
RIP my appeal. It's been only 1 month.
Did u write it formal? Or informal? Or.. just like a small kid xD

**Comment by BarelySmooth** [comment]
> Did u write it formal? Or informal? Or.. just like a small kid xD

I think it was somewhere in the middle 😅 (semi-formal?)

**Comment by Quantum-Codes** [comment]
Lol xD

I'm writing super formal appeals lol

I

**Comment by Quantum-Codes** [comment]
Have replit?

**Comment by BarelySmooth** [comment]
> Have replit?

Yes

**Comment by Quantum-Codes** [comment]
User name

**Comment by BarelySmooth** [comment]
> User name

I guess [BarelySmooth ](https://replit.com/@BarelySmooth)- I haven't used it much

**Comment by Quantum-Codes** [comment]
Oh. Well, how do you even code on github when u can't run code?

**Comment by BarelySmooth** [comment]
> Oh. Well, how do you even code on github when u can't run code?

I can, I run and test stuff on my PC. For this website, GitHub pages builds it automatically.

**Comment by Quantum-Codes** [comment]
Ok

**Pull request closed without merging**
